spring:
  application:
    name: flipzone
  datasource:
      url: jdbc:mysql://localhost:3306/flipzone
      username: root
      password: Password@123
  security:
    user:
      name: admin
      password: Password@123
    jpa:
      hibernate:
        ddl-auto: update
logger:
  level:
    root: INFO
    com.project.flipzone: DEBUG
  file:
    name:logs/flip-zone.log
  pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"



