spring:
  application:
    name: flipzone
  datasource:
      url: jdbc:mysql://localhost:3306/flip_zone
      username: root
      password: Hbbithere@1
#  security:
#    user:
#      name: admin
#      password: Password@123


